version: '3'
services:
  web:
    image: school_management_v1
    command: sh -c "rake assets:clean && rake assets:clobber && rake db:seed && RAILS_ENV=production rake db:migrate && RAILS_ENV=production rake assets:precompile && RAILS_ENV=production puma -p 80"
    ports:
      - "3000:80"
    depends_on:
      - db
    environment:
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: password
      
  db:
    image: postgres:12.3-alpine
    restart: always
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: password